### ISSUE TITLE
Mr. Smite

### ISSUE THREAD

**Issue by Phatcat** [cmangos/classic-db#1]
https://www.youtube.com/watch?v=q6r431x9bPI - 7:22

Mr. smite should not be able to use his AoE stun if he himself is stunned. currently he is.

**Comment by cala** [comment]
Mr. Smite script is handled in SD2 and the spell casts are not explicitly triggered there: they use `CreatureAI::DoCastSpellIfCan(Unit* pTarget, uint32 uiSpell, uint32 uiCastFlags, ObjectGuid uiOriginalCasterGUID)` with no cast flags, so clearly the cast is expected to fail if the caster is impaired.
https://github.com/cmangos/mangos-classic/blob/master/src/scriptdev2/scripts/eastern_kingdoms/deadmines/boss_mr_smite.cpp#L212

So, I assume there is something in the core that allows (or does not prevent) casting when being crowd control.
Anyway, this is more than probably a more generic issue about spell casting of crowd controlled NPCs.
I don't know if this may be related to the recent changes made by @Warlockbugs and I don't see how this could be fixed in the DB or even SD2.

**Comment by Warlockbugs** [comment]
Stun handler had only current cast interruption on application. For preventing new casts you need to look up CheckCast.

**Comment by Phatcat** [comment]
I sort of have an idea of how to sort it by SD2 since he is scripted there (which I didn't know, I will move this issue to the core, sorry), but if it's a generic thing I rather wanna fix it generically in CheckCast.

**Comment by cala** [comment]
You were right to report this issue here in the first place: most non-raid boss AIs are usually handle by ACID.
But it seems this one is not fixable by DB/ACID and requires a more global fix. If you don't mind, I'll close this issue then.
