### ISSUE TITLE
Voodoo Spirit

### ISSUE THREAD

**Issue by Phatcat** [cmangos/classic-db#125]
Voodoo Spirit should move slowly, at around walk speed

**Comment by cala** [comment]
Does @Tobschinski have a way to provide the correct speed values (or aura debuff reducing the actual speed values)?

**Comment by evil-at-wow** [comment]
Yeah, I think I can. I remember posting some data for that NPC in another issue about Zul'Gurub trash, so that means I've seen Voodoo Spirit spawns and the requested data should be in those sniffs somewhere as well.

I'll try to have a look this weekend. Yell at me somewhere next week when I failed to reported back :wink:

**Comment by evil-at-wow** [comment]
I had a look at that sniff from a Zul'Gurub run, and focused on that one Voodoo Spirit GUID I had posted earlier. Just in case: all data is coming from version 3.1.1, build 9806.

As far as aura updates go (SMSG_AURA_UPDATE_ALL/SMSG_AURA_UPDATE packets) I could only find one relevant packet besides a "clear all auras" packet that eventually comes:
```
SMSG_AURA_UPDATE
db 4c 10 a1 3a 30 f1 00 f3 5d 00 00 09 3c 00
```
So that's basically spell 0x5df3 = 24051 in slot 0. Nothing related to speed it appears.

So lacking any other opcodes/packets in the sniff that seemed relevant to a speed change, I had a look at the movement info data sent in the SMSG_COMPRESSED_UPDATE_OBJECT packet for that Voodoo Spirit spawn (the part that also gives us the spawn location etc). The raw bytes for the 9 floats for the speeds in that packet are below (little endian!), and I've annotated them with info based on what's in the core's Object::BuildMovementUpdate() function.
```
// MOVE_WALK
0x26c73140 = 2.777780055999755859375
// MOVE_RUN
0x00000040  = 2.0
// MOVE_RUN_BACK
0x00009040 = 4.5
// MOVE_SWIM
0x721c9740 = 4.72222232818603515625
// MOVE_SWIM_BACK
0x00002040 = 2.5
// MOVE_FLIGHT
0x0000e040 = 7.0
// MOVE_FLIGHT_BACK
0x00009040 = 4.5
// MOVE_TURN_RATE
0xdb0f4940 = 3.1415927410125732421875
// MOVE_PITCH_RATE
0xdb0f4940 = 3.1415927410125732421875
```
I haven't check how speeds are handled in the core, but these values look somewhat weird to me (run speed slower than walk speed?). Do these values make sense for the DB experts? Or should I start investigating possible bugs/errors I made?

**Comment by Phatcat** [comment]
> (run speed slower than walk speed?). Do these values make sense for the DB experts?

I am not an expert at all but it makes perfect sense to me. A bit sloppy on blizzards part but not senseless. Since having a mob walk requires scripted behaviour of some sort, even for blizzard, so a mob which never walks, why even bother to touch the walk speed at all and not just alter the run speed?

**Comment by cala** [comment]
Summoning @Tobschinski who is far used to NPCs speed than me.

**Comment by Tobschinski** [comment]
This is unusual but I guess not impossible.

**Comment by Phatcat** [comment]
Is this so unusual that it's not going to get applied?

**Comment by cala** [comment]
The unusualness of this won't prevent it to be applied. What is preventing it is that I currently have very little time to spend on CMaNGOS and I try to focus myself on a single task for more efficiency. :wink: 
Currently, I'm on BWL rework (along with keeping up with the steady pace of core updates) and it takes longer than I intended at first because things are more complicated than expected.
Next, I'll clean-up as much PR/issues as I can.

**Comment by cala** [comment]
Does that sounds ok?
```sql
-- Fixed speed of NPC 15009 (Voodoo Spirit) in Zul'Gurub
UPDATE creature_template SET SpeedWalk=(7.0 / 2.5), SpeedRun=(14.0 / 7.0) WHERE Entry=15009;
```
